In [1]:
import sqlalchemy as sa
import pandas as pd

In [2]:
test = pd.read_csv('https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz')

test

C:\Users\eltonjr_w\AppData\Local\Temp\ipykernel_17908\1554816339.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  test = pd.read_csv('https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz')

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2021-01-01 00:30:10,2021-01-01 00:36:12,1.0,2.10,1.0,N,142,43,2.0,8.00,3.00,0.5,0.00,0.0,0.3,11.80,2.5
1,1.0,2021-01-01 00:51:20,2021-01-01 00:52:19,1.0,0.20,1.0,N,238,151,2.0,3.00,0.50,0.5,0.00,0.0,0.3,4.30,0.0
2,1.0,2021-01-01 00:43:30,2021-01-01 01:11:06,1.0,14.70,1.0,N,132,165,1.0,42.00,0.50,0.5,8.65,0.0,0.3,51.95,0.0
3,1.0,2021-01-01 00:15:48,2021-01-01 00:31:01,0.0,10.60,1.0,N,138,132,1.0,29.00,0.50,0.5,6.05,0.0,0.3,36.35,0.0
4,2.0,2021-01-01 00:31:49,2021-01-01 00:48:21,1.0,4.94,1.0,N,68,33,1.0,16.50,0.50,0.5,4.06,0.0,0.3,24.36,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369760,NaN,2021-01-25 08:32:04,2021-01-25 08:49:32,NaN,8.80,NaN,NaN,135,82,NaN,21.84,2.75,0.5,0.00,0.0,0.3,25.39,0.0
1369761,NaN,2021-01-25 08:34:00,2021-01-25 09:04:00,NaN,5.86,NaN,NaN,42,161,NaN,26.67,2.75,0.5,0.00,0.0,0.3,30.22,0.0
1369762,NaN,2021-01-25 08:37:00,2021-01-25 08:53:00,NaN,4.45,NaN,NaN,14,106,NaN,25.29,2.75,0.5,0.00,0.0,0.3,28.84,0.0
1369763,NaN,2021-01-25 08:28:00,2021-01-25 08:50:00,NaN,10.04,NaN,NaN,175,216,NaN,28.24,2.75,0.5,0.00,0.0,0.3,31.79,0.0
1369764,NaN,2021-01-25 08:38:00,2021-01-25 08:50:00,NaN,4.93,NaN,NaN,248,168,NaN,20.76,2.75,0.5,0.00,0.0,0.3,24.31,0.0

In [12]:
engine = sa.create_engine("postgresql://root:root@localhost:5433/ny_taxi")

In [8]:
df_iter = pd.read_csv('yellow_tripdata_2021-07.csv.gz', iterator=True, chunksize=100000) # Lê 100k por vez, base com 1.6M

df_first_100k = next(df_iter)

df_first_100k['tpep_pickup_datetime'] = pd.to_datetime(df_first_100k['tpep_pickup_datetime'])
df_first_100k['tpep_dropoff_datetime'] = pd.to_datetime(df_first_100k['tpep_dropoff_datetime'])

In [9]:
df_cabecalho = df_first_100k.head(0)
df_cabecalho

Empty DataFrame
Columns: [VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge]
Index: []

In [15]:
# Comando DDL

print(pd.io.sql.get_schema(df_cabecalho, name='tb_yellow_tripdata', con=engine))

CREATE TABLE tb_yellow_tripdata (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [19]:
%time df_first_100k.to_sql(name='tb_yellow_tripdata', con=engine, if_exists='replace')

CPU times: total: 3.73 s
Wall time: 13.3 s

1000

In [20]:
from time import time

In [21]:
while True: #(Vai dar erro quando não houver mais dados)

    t_start = time()

    df_temp = next(df_iter)

    df_temp['tpep_pickup_datetime'] = pd.to_datetime(df_temp['tpep_pickup_datetime'])
    df_temp['tpep_dropoff_datetime'] = pd.to_datetime(df_temp['tpep_dropoff_datetime'])

    df_temp.to_sql(name='tb_yellow_tripdata', con=engine, if_exists='append')

    t_end = time()

    print('inserted another chunk..., took %.3f seconds' % (t_end - t_start))

inserted another chunk..., took 14.452 seconds
inserted another chunk..., took 15.666 seconds
inserted another chunk..., took 15.316 seconds
inserted another chunk..., took 16.357 seconds
inserted another chunk..., took 15.057 seconds
inserted another chunk..., took 15.034 seconds
inserted another chunk..., took 14.479 seconds
inserted another chunk..., took 14.624 seconds
inserted another chunk..., took 15.527 seconds
inserted another chunk..., took 14.576 seconds
inserted another chunk..., took 15.556 seconds
inserted another chunk..., took 20.018 seconds
inserted another chunk..., took 17.407 seconds
inserted another chunk..., took 18.888 seconds
inserted another chunk..., took 20.079 seconds
inserted another chunk..., took 17.607 seconds
inserted another chunk..., took 17.878 seconds
inserted another chunk..., took 17.236 seconds
inserted another chunk..., took 17.588 seconds
inserted another chunk..., took 17.697 seconds
inserted another chunk..., took 17.145 seconds
inserted another chunk..., took 17.237 seconds
inserted another chunk..., took 18.087 seconds
inserted another chunk..., took 15.466 seconds
inserted another chunk..., took 15.918 seconds

C:\Users\eltonjr_w\AppData\Local\Temp\ipykernel_25392\1455130495.py:5: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_temp = next(df_iter)

inserted another chunk..., took 16.294 seconds
inserted another chunk..., took 14.484 seconds
inserted another chunk..., took 3.042 seconds

StopIteration:

In [22]:
pd.read_sql("select count(*) from tb_yellow_tripdata", con=engine)

     count
0  2821515